import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from '@clerk/nextjs'
import { cn } from "@/lib/utils";
import { NextIntlClientProvider } from "next-intl";
import { Navbar } from "@/modules/HomePage/components/Navbar";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const fontAcademy = Space_Grotesk({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", fontAcademy.className, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider
          appearance={{
            elements: {
              userButtonPopoverFooter: { display: "none" },
            },
          }}
          localization={{
            userButton: {
              action__signOut: "Cerrar sesión",
              action__manageAccount: "Gestionar cuenta",
            },
          }}
        >
          <NextIntlClientProvider>
            <div className="w-full flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-1">
                {children}
              </main>
            </div>
          </NextIntlClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
